name: dart_git
description: Git implementation in dart
version: 0.0.1
author:
homepage: https://github.com/XeGrox/dart_git

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  crypto: ^3.0.1
  path: ^1.7.0
  buffer: ^1.0.7
  equatable: ^2.0.0

dev_dependencies:
  test: ^1.16.8
  pedantic: ^1.9.0
  import_sorter: ^4.4.1

import_sorter:
  comments: false