name: dart_git
description: Git implementation in dart
version: 0.0.1
author:
homepage: https://github.com/XeGrox/dart_git

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  crypto: ^2.1.5
  path: ^1.7.0
  buffer: ^1.0.7
  equatable: ^1.2.5

dev_dependencies:
  test: ^1.15.7
  pedantic: ^1.9.0
  import_sorter: ^4.4.1

import_sorter:
  comments: false